#!/usr/bin/env python

import jwt
import sys
import select

expected_args = 2

if len(sys.argv) == expected_args:
    token = sys.argv[1]
else:
    # Check if there's any input on stdin
    if select.select([sys.stdin], [], [], 0.0)[0]:
        token = sys.stdin.read().strip()
    else:
        print(f"Usage: {sys.argv[0]} token")
        exit(1)

decoded = jwt.decode(token, options={"verify_signature": False}) # works in PyJWT >= v2.0
print(decoded)
