#!/usr/bin/env bash

FILE_W=30;
BLAME_FORMAT="%C(auto) %h %ai";

(
for f in $(git ls-files | grep -E '^[^/]+$');
do
    git --no-pager log --color=always  -n 1 --pretty=format:"$BLAME_FORMAT %C(green)$f%C(auto) %C(dim white)%an%C(auto) %s $(printf "%-*s" )" -- $f; echo
done;
) | sort -k 2 -r
