#!/usr/bin/env bash

# Old way, works but doesn't find all
# git fetch -p && for branch in $(git for-each-ref --format '%(refname) %(upstream:track)' refs/heads | awk '$2 == "[gone]" {sub("refs/heads/", "", $1); print $1}'); do git branch -D "$branch"; done

# New way, using a gh extension (obviously only for github)
gh poi
