#!/usr/bin/env bash

# This script will run a command for each line in stdin
# Usage: cat file.txt | map command

# Check if there is a command to run
# If not, print usage and exit

if [ -z "$1" ]; then
    echo "Usage: cat file.txt | map command"
    exit 1
fi

# Read each line from stdin and run the command
# The command is passed as an argument to the script

IFS=$'\n'
while read -r line; do
    $1 "$line"
done
