#!/usr/bin/env -S uv run --script
# vi: ft=python
# /// script
# requires-python = ">=3.7"
# dependencies = [
#     "jwt",
# ]
# ///

import jwt
import json
import sys

def main():
    # Read the token from stdin
    token = sys.stdin.read().strip()

    if not token:
        print(f"Usage: echo <token> | {sys.argv[0]}")
        exit(1)

    try:
        # If token is surrounded by quotes, remove them (e.g. when token comes from jq)
        if token.startswith('"') and token.endswith('"'):
            token = token[1:-1]
        # Decode the token without verifying the signature
        decoded = jwt.decode(token, options={"verify_signature": False}) # works in PyJWT >= v2.0
        print(json.dumps(decoded, indent=4))
    except Exception as e:
        print(f"Error decoding token: {e}")
        exit(1)

if __name__ == "__main__":
    main()
