#!/usr/bin/env bash

set -e
set -o pipefail

pushd ~/config/nixos/

$EDITOR

if git diff --quiet HEAD -- '*.nix'; then
    echo "No changes detected, exiting."
    popd
    exit 0
fi

alejandra . &>/dev/null \
  || ( alejandra . ; echo "formatting failed!" && exit 1)

git -P diff -U0 '*.nix'

echo "NixOS Rebuilding..."

sudo nixos-rebuild switch --flake .#$(uname -n) | tee nixos-switch.log || (cat nixos-switch.log | grep --color error && exit 1)

current=$(nixos-rebuild list-generations --flake .#$(uname -n) | grep current)

git commit -am "$current"

popd

notify-send -e "NixOS Rebuilt OK!" --icon=software-update-available
