#!/usr/bin/env bash

set -ex

brew upgrade --greedy
bun update --latest -g
mise up
uv tool upgrade --all
rustup update
cargo install $(cargo install --list | egrep '^[a-z0-9_-]+ v[0-9.]+:$' | cut -f1 -d' ')
