#!/usr/bin/env bash

default_max_time=200 # seconds

cleanup() {
	# Kill any child processes
	pkill -P $$
	exit 0
}

cpu_num=$(nproc)

max_time=$1

if [ $# -ne 1 ]; then
    max_time=$default_max_time
fi

echo "Using $cpu_num CPUs for $max_time seconds"

# Register the cleanup function to run on SIGINT and SIGTERM signals
trap cleanup SIGINT SIGTERM

function loop() {
	while true; do
	 	# shellcheck disable=SC2034
		j=1
	done
}

# Start the timer in the background
(
	set -e
	sleep "$max_time"
	echo "Time limit reached ($max_time seconds). Cleaning up..."
	cleanup >/dev/null
) &

for i in $(seq "$cpu_num"); do
	loop "$i" &
done

# Wait for child processes to complete
wait
